# changes here will be overwritten by copier
_src_path: /Users/pcastellazzi/Workspace/code/python-project/
github_repo: https://github.com/pcastellazzi/uparser.git
github_user: pcastellazzi
project_module: uparser
python_version: '3.12'
user_email: pablo.castellazzi@icloud.com
user_name: Pablo Castellazzi
