site_name: uparser

nav:
  - Home: index.md
  - Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
          - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            filters: [ "!^_" ]
            group_by_category: true
            members_order: [source]
            show_category_heading: true
            line_length: 80
            summary: true

theme:
  name: material
  features:
  - content.code.copy
  - content.code.select
  - navigation.expand
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - search.highlight
  - search.share
  - search.suggest
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
