#:schema https://reuse.software/reuse-toml-v1.schema.json
version = 1

[[annotations]]
SPDX-FileCopyrightText = "Copyright © 2025 Pablo Castellazzi <pablo.castellazzi@icloud.com>"
SPDX-License-Identifier = "MIT"
precedence = "override"

path = [
    ".copier-answers.yml",
    ".coveragerc",
    ".cspell.dictionary.txt",
    ".cspell.json",
    ".gitignore",
    ".pdoc-theme/**",
    ".python-version",
    "conftest.py",
    "examples/**",
    "GNUmakefile",
    "prek.toml",
    "pyproject.toml",
    "README.md",
    "ruff.toml",
    "src/**/*.py",
    "tests/**/*.py",
    "uv.lock",
]
